# Generated by Django 5.2 on 2025-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('articulacion_media', 'Articulación con la media'), ('oferta_cerrada', 'Oferta cerrada'), ('oferta_abierta', 'Oferta abierta'), ('reporte_academico', 'Reporte académico'), ('planificacion', 'Planificación')], max_length=50, null=True),
        ),
    ]
